name: make-lint
on: push
jobs:
  lint:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: make lint
